### ISSUE TITLE
serialport@1.7.1 install: `node-pre-gyp install --fallback-to-build` Failed

### ISSUE THREAD

**Issue by TomasPangzi** [charliegerard/leap_sphero#3]
I clone one repo and 'npm install', the Terminal told me that serialport@1.7.1 install: `node-pre-gyp install --fallback-to-build`  failed!

**Comment by charliegerard** [comment]
Hey!

What version of Node are you using? At the moment, it doesn't seem to work with Node 4, I need to work on that.

**Comment by charliegerard** [comment]
Hey!

I just updated the versions of the node modules, would you mind pulling the latest code and try running npm install again?

Should work with the latest version of Node :)

Let me know!

**Comment by TomasPangzi** [comment]
Let me try!

**Comment by TomasPangzi** [comment]
It's Work! Thanks
